version: "2"

run:
  timeout: 5m
  go: "1.25"
  tests: false

linters:
  default: none
  enable:
  - errcheck
  - govet
  - staticcheck
  - ineffassign
  - unused
  - gosec
  - misspell
  - unconvert
  - gocritic
  settings:
    govet:
      enable-all: true
      disable:
      - shadow
      - fieldalignment
    misspell:
      mode: restricted

formatters:
  enable:
  - gofmt
  - goimports
  settings:
    goimports:
      local-prefixes:
      - ybdownload

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
