// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToQueue(arg1, arg2) {
  return window['go']['app']['App']['AddToQueue'](arg1, arg2);
}

export function CancelAllDownloads() {
  return window['go']['app']['App']['CancelAllDownloads']();
}

export function CancelDownload(arg1) {
  return window['go']['app']['App']['CancelDownload'](arg1);
}

export function ClearCompleted() {
  return window['go']['app']['App']['ClearCompleted']();
}

export function FetchMetadata(arg1) {
  return window['go']['app']['App']['FetchMetadata'](arg1);
}

export function GetQueue() {
  return window['go']['app']['App']['GetQueue']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function OpenFile(arg1) {
  return window['go']['app']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['app']['App']['OpenFolder'](arg1);
}

export function RemoveFromQueue(arg1) {
  return window['go']['app']['App']['RemoveFromQueue'](arg1);
}

export function ResetSettings() {
  return window['go']['app']['App']['ResetSettings']();
}

export function RetryDownload(arg1) {
  return window['go']['app']['App']['RetryDownload'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SelectDirectory() {
  return window['go']['app']['App']['SelectDirectory']();
}

export function StartAllDownloads() {
  return window['go']['app']['App']['StartAllDownloads']();
}

export function StartDownload(arg1) {
  return window['go']['app']['App']['StartDownload'](arg1);
}
