// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {updater} from '../models';
import {app} from '../models';
import {youtube} from '../models';
import {options} from '../models';
import {frontend} from '../models';

export function AddToQueue(arg1:string,arg2:string):Promise<core.QueueItem>;

export function AnalyzeMediaFile(arg1:string):Promise<core.MediaInfo>;

export function CancelAllDownloads():Promise<void>;

export function CancelConversion(arg1:string):Promise<void>;

export function CancelDownload(arg1:string):Promise<void>;

export function CheckFFmpeg():Promise<boolean|string>;

export function CheckForUpdate():Promise<updater.UpdateInfo>;

export function ClearCompleted():Promise<void>;

export function ClearCompletedConversions():Promise<void>;

export function DownloadFFmpeg():Promise<void>;

export function DownloadUpdate():Promise<string>;

export function FetchMetadata(arg1:string):Promise<core.VideoMetadata>;

export function GenerateWaveform(arg1:string,arg2:number):Promise<Array<number>>;

export function GetAppVersion():Promise<string>;

export function GetConversionJobs():Promise<Array<core.ConversionJob>>;

export function GetConversionPresets():Promise<Array<core.ConversionPreset>>;

export function GetConversionPresetsByCategory(arg1:string):Promise<Array<core.ConversionPreset>>;

export function GetFFmpegStatus():Promise<app.FFmpegStatus>;

export function GetQueue():Promise<Array<core.QueueItem>>;

export function GetSettings():Promise<core.Settings>;

export function GetTrendingVideos(arg1:string,arg2:number):Promise<youtube.SearchResponse>;

export function GetUpdateInfo():Promise<updater.UpdateInfo>;

export function ImportURLs(arg1:Array<string>,arg2:string):Promise<app.ImportResult>;

export function InstallUpdate():Promise<void>;

export function IsValidYouTubeURL(arg1:string):Promise<boolean>;

export function OnSecondInstance(arg1:options.SecondInstanceData):Promise<void>;

export function OnUrlOpen(arg1:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function OpenReleasePage():Promise<void>;

export function RemoveConversionJob(arg1:string):Promise<void>;

export function RemoveFromQueue(arg1:string):Promise<void>;

export function ResetSettings():Promise<core.Settings>;

export function RetryDownload(arg1:string):Promise<void>;

export function SaveSettings(arg1:core.Settings):Promise<void>;

export function SearchYouTube(arg1:string,arg2:number):Promise<youtube.SearchResponse>;

export function SelectDirectory():Promise<string>;

export function SelectFile(arg1:string,arg2:Array<frontend.FileFilter>):Promise<string>;

export function SelectMediaFile():Promise<string>;

export function SetPendingDeepLink(arg1:string):Promise<void>;

export function StartAllDownloads():Promise<void>;

export function StartConversion(arg1:string,arg2:string,arg3:string):Promise<core.ConversionJob>;

export function StartConversionWithTrim(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<core.ConversionJob>;

export function StartCustomConversion(arg1:string,arg2:string,arg3:Array<string>):Promise<core.ConversionJob>;

export function StartDownload(arg1:string):Promise<void>;
