// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {app} from '../models';

export function AddToQueue(arg1:string,arg2:string):Promise<core.QueueItem>;

export function CancelAllDownloads():Promise<void>;

export function CancelDownload(arg1:string):Promise<void>;

export function CheckFFmpeg():Promise<boolean|string>;

export function ClearCompleted():Promise<void>;

export function FetchMetadata(arg1:string):Promise<core.VideoMetadata>;

export function GetQueue():Promise<Array<core.QueueItem>>;

export function GetSettings():Promise<core.Settings>;

export function ImportURLs(arg1:Array<string>,arg2:string):Promise<app.ImportResult>;

export function IsValidYouTubeURL(arg1:string):Promise<boolean>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenFolder(arg1:string):Promise<void>;

export function RemoveFromQueue(arg1:string):Promise<void>;

export function ResetSettings():Promise<core.Settings>;

export function RetryDownload(arg1:string):Promise<void>;

export function SaveSettings(arg1:core.Settings):Promise<void>;

export function SelectDirectory():Promise<string>;

export function StartAllDownloads():Promise<void>;

export function StartDownload(arg1:string):Promise<void>;
