// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToQueue(arg1, arg2) {
  return window['go']['app']['App']['AddToQueue'](arg1, arg2);
}

export function AnalyzeMediaFile(arg1) {
  return window['go']['app']['App']['AnalyzeMediaFile'](arg1);
}

export function CancelAllDownloads() {
  return window['go']['app']['App']['CancelAllDownloads']();
}

export function CancelConversion(arg1) {
  return window['go']['app']['App']['CancelConversion'](arg1);
}

export function CancelDownload(arg1) {
  return window['go']['app']['App']['CancelDownload'](arg1);
}

export function CheckFFmpeg() {
  return window['go']['app']['App']['CheckFFmpeg']();
}

export function CheckForUpdate() {
  return window['go']['app']['App']['CheckForUpdate']();
}

export function ClearCompleted() {
  return window['go']['app']['App']['ClearCompleted']();
}

export function ClearCompletedConversions() {
  return window['go']['app']['App']['ClearCompletedConversions']();
}

export function DownloadFFmpeg() {
  return window['go']['app']['App']['DownloadFFmpeg']();
}

export function DownloadUpdate() {
  return window['go']['app']['App']['DownloadUpdate']();
}

export function FetchMetadata(arg1) {
  return window['go']['app']['App']['FetchMetadata'](arg1);
}

export function GenerateWaveform(arg1, arg2) {
  return window['go']['app']['App']['GenerateWaveform'](arg1, arg2);
}

export function GetAppVersion() {
  return window['go']['app']['App']['GetAppVersion']();
}

export function GetConversionJobs() {
  return window['go']['app']['App']['GetConversionJobs']();
}

export function GetConversionPresets() {
  return window['go']['app']['App']['GetConversionPresets']();
}

export function GetConversionPresetsByCategory(arg1) {
  return window['go']['app']['App']['GetConversionPresetsByCategory'](arg1);
}

export function GetFFmpegStatus() {
  return window['go']['app']['App']['GetFFmpegStatus']();
}

export function GetQueue() {
  return window['go']['app']['App']['GetQueue']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetTrendingVideos(arg1, arg2) {
  return window['go']['app']['App']['GetTrendingVideos'](arg1, arg2);
}

export function GetUpdateInfo() {
  return window['go']['app']['App']['GetUpdateInfo']();
}

export function ImportURLs(arg1, arg2) {
  return window['go']['app']['App']['ImportURLs'](arg1, arg2);
}

export function InstallUpdate() {
  return window['go']['app']['App']['InstallUpdate']();
}

export function IsValidYouTubeURL(arg1) {
  return window['go']['app']['App']['IsValidYouTubeURL'](arg1);
}

export function OnSecondInstance(arg1) {
  return window['go']['app']['App']['OnSecondInstance'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['app']['App']['OpenFile'](arg1);
}

export function OpenFolder(arg1) {
  return window['go']['app']['App']['OpenFolder'](arg1);
}

export function OpenReleasePage() {
  return window['go']['app']['App']['OpenReleasePage']();
}

export function RemoveConversionJob(arg1) {
  return window['go']['app']['App']['RemoveConversionJob'](arg1);
}

export function RemoveFromQueue(arg1) {
  return window['go']['app']['App']['RemoveFromQueue'](arg1);
}

export function ResetSettings() {
  return window['go']['app']['App']['ResetSettings']();
}

export function RetryDownload(arg1) {
  return window['go']['app']['App']['RetryDownload'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SearchYouTube(arg1, arg2) {
  return window['go']['app']['App']['SearchYouTube'](arg1, arg2);
}

export function SelectDirectory() {
  return window['go']['app']['App']['SelectDirectory']();
}

export function SelectFile(arg1, arg2) {
  return window['go']['app']['App']['SelectFile'](arg1, arg2);
}

export function SelectMediaFile() {
  return window['go']['app']['App']['SelectMediaFile']();
}

export function StartAllDownloads() {
  return window['go']['app']['App']['StartAllDownloads']();
}

export function StartConversion(arg1, arg2, arg3) {
  return window['go']['app']['App']['StartConversion'](arg1, arg2, arg3);
}

export function StartConversionWithTrim(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['StartConversionWithTrim'](arg1, arg2, arg3, arg4, arg5);
}

export function StartCustomConversion(arg1, arg2, arg3) {
  return window['go']['app']['App']['StartCustomConversion'](arg1, arg2, arg3);
}

export function StartDownload(arg1) {
  return window['go']['app']['App']['StartDownload'](arg1);
}
